{{- if default false .Values.flux.flagger.enabled }}
{{- $fullName := include "standard-application.fullname" . -}}
---
apiVersion: {{ .Values.flux.flagger.apiVersion }}
kind: Canary
metadata:
  name: {{ $fullName }}
spec:
  {{- with .Values.flux.flagger.spec }}
    {{- toYaml . | nindent 2 }}
  {{- end }}

{{- end }}
